### PR TITLE
Support `requred` parameter for body

### PR DESCRIPTION
**Pull request by MissiaL**
I came across the fact that in my project the body is always a required parameter. I came up with such a solution. He may not be the best, but nothing came to my head

image

### CODE REVIEW

**Comment by tfranzel** [comment]
haven't thought of that before, but i think a setting is not the right choice. i believe that this can be solved via introspection. settings should be absolute fallback if its impossible to determine the info by other means imho.

couldn't you just say: if at least one field is required, the request has to be present? (required=True)
Otherwise zero required fields makes the request body optional (required=False)

**Comment by MissiaL** [comment]
I agree with you. Let me try to redo my pull request

**Comment by MissiaL** [comment]
Done. Could you check?

**Comment by tfranzel** [comment]
thank you! looks awesome. i just removed that one action, which was covered multiple times because the test is already fairly large.

**Pull request merged**
