### PR TITLE
Adding field serializers support

### PR DESCRIPTION
**Pull request by MissiaL**
In some cases, you can specify your serializer
I think this is a useful fix.

### CODE REVIEW

**Comment by MissiaL** [comment]
I fixed linter errors but it still failed

**Comment by tfranzel** [comment]
```
drf_spectacular/plumbing.py:5:39: E231 missing whitespace after ','
tests/test_extend_schema.py:60:1: E305 expected 2 blank lines after class or function definition, found 1
flake8 failed
```
try running tox locally. runtests.py should also raise the linting error.

regarding the change: i have to think a bit more about the implications.

**Comment by MissiaL** [comment]
> regarding the change: i have to think a bit more about the implications.

I did it his by analog with [this](https://drf-yasg.readthedocs.io/en/stable/custom_spec.html#support-for-serializermethodfield)
My plans are to migrate a large project to use your package. I gradually deal with some emerging issues and try to solve them

**Comment by tfranzel** [comment]
never seen it used like that so good catch! However it bypassed some warnings on misusage (for which there are no tests yet). fixed it myself because it was hard to explain. thanks!

**Pull request merged**
