### PR TITLE
improve mypy typing #600

### PR DESCRIPTION
**Pull request by tfranzel**
Type improvements. This will fix some of the `mypy --strict` flags. Green for the following flags. Commented out flags still fail.

```bash
mypy --config-file tox.ini drf_spectacular \
--warn-unused-configs \ 
--strict-equality \
--no-implicit-optional \ 
--warn-redundant-casts \
--disallow-untyped-decorators \ 
--disallow-subclassing-any \ 
--warn-unused-ignores \ 
#--check-untyped-defs \
#--warn-return-any \
#--no-implicit-reexport \
#--disallow-incomplete-defs \
#--disallow-any-generics \
#--disallow-untyped-calls \
#--disallow-untyped-defs \
```

### CODE REVIEW

**Comment by johnthagen** [comment]
I'm sure you know this already, but just FYI you can put these settings into the Mypy config file too to avoid having to pass them each time into the command line.

**Comment by tfranzel** [comment]
yeah thx, i know. had this command in a shell script for playing around, but at some point it should be included in `tox.ini` for sure.

**Comment by sshishov** [comment]
When the change is going to be released?

**Comment by tfranzel** [comment]
@sshishov what exactly is your use-case in benefiting from this PR? 

we will likely never be able to pass full`--strict` without hundreds of `type: ignore` due to the dynamic nature of this package. It is good to have nonetheless, but the user is likely only to really benefit from changes to `utils.py`

**Comment by tfranzel** [comment]
in that case I will revisit this PR when I have some spare time.

**Comment by sshishov** [comment]
Hello @tfranzel and @johnthagen . My use case is the subclass of AutoSchema and extend it to use with `drf-rw-serializers` which we have in Blueprints. As we are using `mypy` with almost strict configuration, any code which is called untyped objects or subclassed from untyped objects, are warned.

Definitely we can add the ignore and completely abandon typing hints but we would like to use the typing hints as it make the coding more fun and easy.

Do not get me wrong, guys, just adding typing is beneficial as IDE start helping a lot in that case. Also typed code much easier to read and extend as you know that are the parameters, what their types and kind of how to use them.

Thank you! And sorry for the longread...

**Comment by tfranzel** [comment]
Hey guys, so I revised this PR again. I think it is a lot better now and a step in the right direction, but not perfect and not complete by any stretch of the imagination. not sure exactly how far we can go further, but passing --strict is imho almost impossible due to the dynamic nature of the package. 

any further iteration should be smaller though. feel free to give feedback.

**Comment by johnthagen** [comment]
@tfranzel Wanted to report I just updated to the latest `drf-spectacular` and was able to remove a bunch of `# type: ignore` comments because of this, thanks!

**Pull request merged**
