### PR TITLE
Safer field map serializer

### PR DESCRIPTION
**Pull request by jayvdb**
Related to #79

### CODE REVIEW

**Comment by jayvdb** [comment]
Feel free to abandon this if you have time to find a better solution.
This is for a new project trialing drf-spectacular, and is the only patch needed to get a moderately large in-house schema to build.
```
Schema generation summary:
Warnings: 162 (72 unique)
Errors:   50 (8 unique)
```

**Comment by tfranzel** [comment]
the manyrelated should be fixed with e7c8108

regarding the other change. i like what you did there, but i'm hesitant to include it (currently). my rational is that people will more likely open issues when something like this happens. that way we can identify&fix more corner cases that are not covered by the tests or the contributor usage. if we only "warn" on those issues i think we lessen the chance of people opening an issue for it. i think the project will benefit from the occasional raised exception :smile: if catching is a matter of last resort it's a different story.

on that matter, does your build run with the fix or are there other things throwing exceptions?

**Comment by jayvdb** [comment]
The fact that drf-spectacular didn't raise exceptions on my first project was what drew me in.  I think a 'raise exception' mode to help people diagnose the problems would be helpful, and they would opt-in to improving the tool by enabling that when they want those remaining bits of their schema to be more accurate.  It is in their own best interest.  But forcing them is counter productive - they formost want usable software.  It could even be a CLI option, and enabled by default with a hint on how to disable it(perhaps even co-opting `--verbosity 3`).  It should be disabled by default so that the code paths were it is enabled are very clear.  It decidedly unhelpful for it to occur when invoked via the `SpectacularAPIView`, as you are not helping a deployed site by breaking their API view with an exception.

What is more, everywhere else in the code these warnings are used instead of exceptions.  I am confused why when I propose a PR to follow suit, you have a sudden change of philosophy.

If you do wish to proceed with this, you can cherry-pick that commit which I kept separate for that purpose, or discard the other now conflicted commit from this PR if you wish to do a merge operation.  Otherwise close, and we'll muddle on.

**Comment by tfranzel** [comment]
sry i should have made that a more clear. of course we don't want an exception spree. 

i tried to use the try excepts where "external" code could break (like accessing the queryset). this bug however was an broken assumption inside spectacular about the m2m field. those "internal" bugs i would like to have surfacing. wrapping the `map_serializer_field` would have obfuscated that broken assumption. i think its too broad like that. that was my point. 

i believe we have solved a lot of common and edge cases by now and this should happen very rarely now. also thanks you. i have run spectacular on several medium to large size projects. i believe you did the same. the project has progressed a lot and i think its a good sign that we rarely see any exceptions now. of course we want to keep it that way.

but at the end of the day you are absolutely right about the user. i'll give it so thought on how to deal with it.

**Comment by jayvdb** [comment]
In Python type introspection, any use of "`.`" on someone elses object is potentially invoking external code.  And in Django there is an extensive library of hacks hinged on each and every "`.`" possible.  Anyways, I dont rely on this PR, it has been bitrotted, and dont intend to waste further time on it.

**Pull request closed without merging**
