### PR TITLE
fix sidecar install command

### PR DESCRIPTION
**Pull request by ahmetveburak**

### CODE REVIEW

**Comment by tfranzel** [comment]
thanks for the PR @ahmetveburak. this is as intended and will start working once i do a release later today. the README was a bit ahead.

`drf-spectacular[sidecar]` will install `drf-spectacular` with the optional dependency `drf-spectcular-sidecar`. the sidecar alone will not get you very far.

**Comment by ahmetveburak** [comment]
I am just trying to get `drf-spectacular` work for me and tried all the instructions, commands on the readme file but still not works :D 
I got the error for `sidecar` and just want to correct it. Not a big deal, thanks :)

**Comment by tfranzel** [comment]
following https://github.com/tfranzel/drf-spectacular#installation will do perfectly fine. then this https://github.com/tfranzel/drf-spectacular#take-it-for-a-spin

https://github.com/tfranzel/drf-spectacular#self-contained-ui-installation is only relevant if you are in a corporate setting where you don't have a direct internet connection and cannot retrieve SwaggerUI/Redoc from CDN.

**Comment by ahmetveburak** [comment]
I repeat the documentation 4 times for 2 of my projects. Now I created a simple app for testing that have only viewset. But I still have an empty schema.yml. Before open an issue, I'm trying versioning and looking issues to find what am I missing.

Built-in django generateschema command works well but spectacular still generates an empty schema.

**Comment by ahmetveburak** [comment]
Finally it worked. Thanks a lot for the tool. Explicitly providing in the view helped. Found in your answer.
https://github.com/tfranzel/drf-spectacular/issues/364#issuecomment-818776038

**Comment by tfranzel** [comment]
it's a common error. `generateschema` does not do versioning, thats why its working. our version system is pretty nice but also relentless. its the price we pay for it. maybe i'll update the readme with a note.

**Pull request closed without merging**
