### PR TITLE
Add test for related field warning

### PR DESCRIPTION
**Pull request by MissiaL**
In my project i got warning
```
could not resolve serializer field ...
```
I use the RelatedSerializerField 

I wrote a test. Could you see the problem?

### CODE REVIEW

**Comment by tfranzel** [comment]
hey @MissiaL. didn't we discuss this in https://github.com/tfranzel/drf-spectacular/issues/21#issuecomment-608458032 ?

it is unclear to me what should be resolved for this custom `RelatedField`. can you propose an idea for resolving that type automatically? imho `RelatedField` like that is underspecified for schema extraction. If it were based on`PrimaryKeyRelatedField` i guess it would work out of the box. 

if you want to keep `RelatedField` as base you would have to annotate with @extend_schema_field`.

**Comment by MissiaL** [comment]
Sorry. I completely forgot that I was creating a past problem

I think for this field it would be possible to ignore the waring and not display it.
I also looked at the implementation in drf_yasg and it did the same
https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/inspectors/field.py#L250

**Comment by tfranzel** [comment]
the intention of the warning, as i envisioned it, was to notify the user of things that might not be what he expects. the warning does serve a purpose here, at least it would for me. to me its says either change the base class or use `@extend_schema_field` and clarify what is to be expected here (because string fallback might be wrong). 

if it is non-accessible library code you can now use the plugin system with `OpenApiSerializerFieldExtension`.

**Comment by tfranzel** [comment]
what we can do is a explicit warning for that case, as others might also trip over this.

**Pull request closed without merging**
