### PR TITLE
add django-rest-framework-gis upstream approach

### PR DESCRIPTION
**Pull request by tfranzel**
alternate approach to #67 (#38)

further discussion in #743

### CODE REVIEW

**Comment by joey-kevala** [comment]
Thanks @tfranzel, it's great that this solution extracts a lot more info directly from the rest_framework_gis autoschema compared to how I did it. 

Tried this out, and it's still affected in the same way as my PR was from the bad schema definitions in rest_framework_gis. Any fields using generic `GeometryField` or `GeometryCollectionField` geodjango fields will be converted to invalid OpenAPI and not be renderable in redoc, etc (I personally don't use those fields which is why it wasn't a huge deal to me). Wouldn't be a difficult upstream fix though... the problem is [right here](https://github.com/openwisp/django-rest-framework-gis/blob/master/rest_framework_gis/schema.py#L58). Haven't fully verified this but I think that snippet just needs to be converted to look something like this:
```
'oneOf': [
    {
        "type": "object",
        "properties": {
            GEO_FIELD_TO_SCHEMA[models.PointField]
        },
    },
    {
        "type": "object",
        "properties": {
            GEO_FIELD_TO_SCHEMA[models.LineStringField]
        },
    },
    {
        "type": "object",
        "properties": {
            GEO_FIELD_TO_SCHEMA[models.PolygonField
        },
    }
],
```

And a more minor issue in their schema in the [example for PolygonField](https://github.com/openwisp/django-rest-framework-gis/blob/master/rest_framework_gis/schema.py#L44) needs another layer of nesting in the array.

One other issue I noticed when testing your PR that my PR did handle correctly is cases with multiple geometry fields. This PR only converts the main `geo_field` into geojson, but if there are other geometry fields they'll be left as string. For example a model with multiple geometry fields could look like this:
```
{
    "type": "Feature",
    "geometry": {
        "type": "LineString",
        "coordinates": [[0,1],[0,2]]
    }
    "properties": {
        "other_geometry_field": {
            "type": "Point",
            "coordinates": [0,1]
        }
    }
}
```
But this PR generates the schema for `other_geometry_field` as a string. (For me it's quite common to have models like this with multiple geometry fields)

**Comment by tfranzel** [comment]
Hey @joey-kevala 

I gave this some more thought. DRF has pretty much abandoned the idea of every lib having their own `AutoSchema` implementation. So the code I based this elaborate contraption on has an expiration date.

In #67 I wrote the schema generation from scratch. Her, I only hooked into the upstream code. I think the solution lies in the middle.  At this point I believe the most reasonable approach is to "fork" the upstream code into our code base and then fix the issues you described. Furthermore, this would be in line with all the other 3rd party libs we support.

I will create yet another PR for this. It would be a tremendous help if you then could review that new PR as you have more practical knowledge than me in this regard.

**Comment by tfranzel** [comment]
while porting the code I found that it is quite broken, but you already noticed that. I just thought there were 1-2 small issues but it turns out the whole construction is problematic imho. New PR will come to get this finally over with :smile:

**Comment by tfranzel** [comment]
this PR got superseded by https://github.com/tfranzel/drf-spectacular/pull/746. discussion&feedback continues there.

**Pull request closed without merging**
